config/routes.rb
Rails.application.routes.draw do
  resources :user_informations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_information.rb
class UserInformation < ApplicationRecord

    STRING_REGEX = /\A[a-zA-Z]+\z/
    INT_REGEX = /\A\d+\z/
    MESSAGE = "only allows letters"

    validates :name,         presence: true,   format: { with: STRING_REGEX, message: MESSAGE }
    validates :first_name,   presence: true,   format: { with: STRING_REGEX, message: MESSAGE }
    validates :last_name,    presence: true,   format: { with: STRING_REGEX, message: MESSAGE }
    validates :phone_number, presence: true,   format: { with: INT_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_informations_controller.rb
class UserInformationsController < ApplicationController
  before_action :set_user_information, only: %i[ show edit update destroy ]

  # GET /user_informations or /user_informations.json
  def index
    @user_informations = UserInformation.all
  end

  # GET /user_informations/1 or /user_informations/1.json
  def show
  end

  # GET /user_informations/new
  def new
    @user_information = UserInformation.new
  end

  # GET /user_informations/1/edit
  def edit
  end

  # POST /user_informations or /user_informations.json
  def create
    @user_information = UserInformation.new(user_information_params)

    respond_to do |format|
      if @user_information.save
        format.html { redirect_to @user_information, notice: "User information was successfully created." }
        format.json { render :show, status: :created, location: @user_information }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_informations/1 or /user_informations/1.json
  def update
    respond_to do |format|
      if @user_information.update(user_information_params)
        format.html { redirect_to @user_information, notice: "User information was successfully updated." }
        format.json { render :show, status: :ok, location: @user_information }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_informations/1 or /user_informations/1.json
  def destroy
    @user_information.destroy
    respond_to do |format|
      format.html { redirect_to user_informations_url, notice: "User information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_information
      @user_information = UserInformation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_information_params
      params.require(:user_information).permit(:name, :first_name, :last_name, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_informations_helper.rb
module UserInformationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Customer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_informations/_form.html.erb
<%= form_with(model: user_information, local: true) do |form| %>
  <% if user_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_information.errors.count, "error") %> prohibited this user_information from being saved:</h2>

      <ul>
      <% user_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_informations/edit.html.erb
<h1>Editing User Information</h1>

<%= render 'form', user_information: @user_information %>

<%= link_to 'Show', @user_information %> |
<%= link_to 'Back', user_informations_path %>

app/views/user_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Informations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_informations.each do |user_information| %>
      <tr>
        <td><%= user_information.name %></td>
        <td><%= user_information.first_name %></td>
        <td><%= user_information.last_name %></td>
        <td><%= user_information.phone_number %></td>
        <td><%= link_to 'Show', user_information %></td>
        <td><%= link_to 'Edit', edit_user_information_path(user_information) %></td>
        <td><%= link_to 'Destroy', user_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Information', new_user_information_path %>

app/views/user_informations/new.html.erb
<h1>New User Information</h1>

<%= render 'form', user_information: @user_information %>

<%= link_to 'Back', user_informations_path %>

app/views/user_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_information.name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user_information.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_information.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user_information.phone_number %>
</p>

<%= link_to 'Edit', edit_user_information_path(@user_information) %> |
<%= link_to 'Back', user_informations_path %>